const DATA = {
  LOAD: "LOAD_DATA",
  LOAD_SUCCESS: "DATA_LOAD_SUCCESS",
  LOAD_FAILURE: "DATA_LOAD_FAIL"
};

const FAV_BOOKS = {
  LOAD_FAV_BOOKS: "LOAD_FAV_BOOKS",
  FAV_BOOKS_SUCCESS: "FAV_BOOKS_SUCCESS",
  FAV_BOOKS_FAILURE: "FAV_BOOKS_FAILURE"
};

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export { DATA, FAV_BOOKS };
